// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATDssq-cNpB96b13nMsuVMsrrmOILB_Ws',
    appId: '1:606064781117:web:ac2796fc8a98bc071bc754',
    messagingSenderId: '606064781117',
    projectId: 'projeto-robocop-a0fe9',
    authDomain: 'projeto-robocop-a0fe9.firebaseapp.com',
    databaseURL: 'https://projeto-robocop-a0fe9-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-robocop-a0fe9.appspot.com',
    measurementId: 'G-WJ6Z9EVTBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8vu5Ztf-V4DRSswjBBanrlBzGqrxOLFQ',
    appId: '1:606064781117:android:6cbaeba09795f5ee1bc754',
    messagingSenderId: '606064781117',
    projectId: 'projeto-robocop-a0fe9',
    databaseURL: 'https://projeto-robocop-a0fe9-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-robocop-a0fe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5v9SfCk1eeXU55xVQBEdVzBC6oz8F38Y',
    appId: '1:606064781117:ios:69d58f6e6b28c7781bc754',
    messagingSenderId: '606064781117',
    projectId: 'projeto-robocop-a0fe9',
    databaseURL: 'https://projeto-robocop-a0fe9-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-robocop-a0fe9.appspot.com',
    androidClientId: '606064781117-1a9vq8t3t6csirf70egom8a2apronvgs.apps.googleusercontent.com',
    iosClientId: '606064781117-4tt7la721qht2373hdtmircuk61rbott.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5v9SfCk1eeXU55xVQBEdVzBC6oz8F38Y',
    appId: '1:606064781117:ios:0c24b8a5df727e021bc754',
    messagingSenderId: '606064781117',
    projectId: 'projeto-robocop-a0fe9',
    databaseURL: 'https://projeto-robocop-a0fe9-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-robocop-a0fe9.appspot.com',
    androidClientId: '606064781117-1a9vq8t3t6csirf70egom8a2apronvgs.apps.googleusercontent.com',
    iosClientId: '606064781117-onjm21t89ro5crk71ue82mr1ucpd62j3.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
