// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAw0rVsYkA5OZgwBpg1ap0MeB-CuvVZUE',
    appId: '1:865453518820:web:031b6e1ee0fea526a7a1f1',
    messagingSenderId: '865453518820',
    projectId: 'projeto-robocop',
    authDomain: 'projeto-robocop.firebaseapp.com',
    storageBucket: 'projeto-robocop.appspot.com',
    measurementId: 'G-80G8C20XWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjRCcAq4lTxFBjn7Yg3YRDNV9W2XAPSlo',
    appId: '1:865453518820:android:e843aca0830ceb9aa7a1f1',
    messagingSenderId: '865453518820',
    projectId: 'projeto-robocop',
    storageBucket: 'projeto-robocop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD05bw5_GIXi3cGhLFnXmMlVSO18rpNxr4',
    appId: '1:865453518820:ios:10b8ce45895edbc1a7a1f1',
    messagingSenderId: '865453518820',
    projectId: 'projeto-robocop',
    storageBucket: 'projeto-robocop.appspot.com',
    iosClientId: '865453518820-d3qetflsuactehv57feff87uv8elkhg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.trabalho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD05bw5_GIXi3cGhLFnXmMlVSO18rpNxr4',
    appId: '1:865453518820:ios:4770197ea427a9a9a7a1f1',
    messagingSenderId: '865453518820',
    projectId: 'projeto-robocop',
    storageBucket: 'projeto-robocop.appspot.com',
    iosClientId: '865453518820-b8cdm9n90p7cv0sd4ls7e3jhf8nl42nk.apps.googleusercontent.com',
    iosBundleId: 'com.example.trabalho.RunnerTests',
  );
}
